# NFC ピンを GPIO として使用
CONFIG_NFCT_PINS_AS_GPIOS=y

# 入力・ポインティング
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

# SPI
CONFIG_SPI=y
CONFIG_SPI_NRFX=y

# PMW3610 トラックボールセンサー（badjeff driver）
CONFIG_PMW3610_ALT=y

# BLE
CONFIG_ZMK_BLE=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# バッテリー
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# ZMK Studio（USB カスタマイズツール）
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# スリープ設定
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# RGB LED ウィジェット
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=40
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=20
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=2
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=3
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=4
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=7
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=4
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=0
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=0
CONFIG_RGBLED_WIDGET_LAYER_7_COLOR=0
